// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagerApp.Veri;

#nullable disable

namespace TaskManagerApp.Migrations
{
    [DbContext(typeof(UygulamaDbBaglami))]
    partial class UygulamaDbBaglamiModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("TaskManagerApp.Modeller.Gorev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Durum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SonTarih")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjeId");

                    b.ToTable("Gorevler");
                });

            modelBuilder.Entity("TaskManagerApp.Modeller.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("TaskManagerApp.Modeller.Proje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Projeler");
                });

            modelBuilder.Entity("TaskManagerApp.Modeller.Gorev", b =>
                {
                    b.HasOne("TaskManagerApp.Modeller.Proje", "Proje")
                        .WithMany("Gorevler")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proje");
                });

            modelBuilder.Entity("TaskManagerApp.Modeller.Proje", b =>
                {
                    b.HasOne("TaskManagerApp.Modeller.Kullanici", "Kullanici")
                        .WithMany("Projeler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("TaskManagerApp.Modeller.Kullanici", b =>
                {
                    b.Navigation("Projeler");
                });

            modelBuilder.Entity("TaskManagerApp.Modeller.Proje", b =>
                {
                    b.Navigation("Gorevler");
                });
#pragma warning restore 612, 618
        }
    }
}
